# GUI option configuration:
gui: 
  steps_for_sample_size: 50
  min_sample: 50
  default_sample: 100
  min_bi_encoding: 0
  max_bi_encoding: 0.75
  default_bi_encoding: 0.25
  max_input_box: 10
  min_input_box: 1
  default_input_box: 3
  overflow_min: 1
  overflow_max: 10
  default_overflow: 3

# AI model selection
bi_encoder_model_name: "sentence-transformers/all-MiniLM-L6-v2"
cross_encoder_model_name: "cross-encoder/stsb-roberta-base"