# GUI option configuration:
gui: 
  steps_for_sample_size: 50
  min_sample: 0
  default_sample: 10
  min_bi_encoding: 0
  max_bi_encoding: 0.75
  default_bi_encoding: 0.25
  max_input_box: 10
  min_input_box: 0
  default_input_box: 1
  overflow_min: 1
  overflow_max: 10
  default_overflow: 3

# AI model selection
bi_encoder_model_name: "sentence-transformers/all-MiniLM-L6-v2"
cross_encoder_model_name: "cross-encoder/stsb-roberta-base"

scraper:
  browser: "msedge"
  headless: true
  data_batch_size: 1000 # Test value, don't use this value for actual data scraping pls...
  request_limit: 600 # Number of requests made per minute, avoids rate limits and is just nice for the website